@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgxNzE3NTl9.P_NFu75jIPp4E-sUo8A0blSAJRFR9O5gZ0lmEx-6JkU
### movies index request
GET http://localhost:3000/movies
### movie show request
GET http://localhost:3000/movies/3
### movie create request
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Spider-Man: No Way Home",
  "year": 2017,
  "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man."
}
### movie delete request
DELETE  http://localhost:3000/movies/6
### actor delete request
DELETE  http://localhost:3000/actors/10.json
### movie delete request
PATCH   http://localhost:3000/movies/7
Content-Type: application/json

{
  "year":2021
}
### actors index request
GET http://localhost:3000/actors
### create request
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Robert",
  "last_name": "Downey, Jr.",
  "known_for": "Iron Man",
  "movie_id": 2
}

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "jason",
  "email": "jason@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "jason@test.com",
  "password": "password"
}
### Movies create with auth
POST http://localhost:3000/movies.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "title": "Spider-Man: No Way Home",
  "year": 2017,
  "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man."
}