### movies index request
GET http://localhost:3000/movies
### movie show request
GET http://localhost:3000/movies/3
### movie create request
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Spider-Man: No Way Home",
  "year": 2017,
  "plot": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man."
}
### movie delete request
DELETE  http://localhost:3000/movies/6
### movie delete request
PATCH   http://localhost:3000/movies/7
Content-Type: application/json

{
  "year":2021
}