# actor = Actor.create(first_name: "Nathan", last_name: "Fillion", known_for: "Firefly")
# actor = Actor.create({ first_name: "Benedict", last_name: "Cumberbatch", known_for: "Sherlock" })
actor = Actor.create({ first_name: "Ana", last_name: "de Armas", known_for: "Blade Runner 2049" })
actor = Actor.create({ first_name: "Tom", last_name: "Holland", known_for: "Spiderman: Homecoming" })
actor = Actor.create({ first_name: "Ryan", last_name: "Reynolds", known_for: "Deadpool" })
